In [1]:
import numpy as np
import math
import time
import scipy
from math import pi, exp, factorial, sin, cos
from matplotlib import pyplot as plt

In [2]:
def QR_Householder(A): #UPGRADE: Let the algorithm accept non-square matrices?
    n = np.shape(A)[0]
    R = np.copy(A)
    Q = np.eye(n)
    V = np.zeros((n,n))
    for k in range(0,n):
        x = R[k:,k]
        e1 = np.zeros(np.size(x))
        e1[0] = 1
        v = np.sign(x[0])*np.linalg.norm(x,2)*e1 + x
        v = v/np.linalg.norm(v,2)
        V[0:(n-k),k] = v
        F = np.eye(n-k,n-k) - 2*np.outer(v,v)
        R[k:,k:] =  F@R[k:,k:]
        Q[k:,:] = F@np.copy(Q[k:,:]) #Modification to get Q.
    return R, V, np.matrix.getH(Q)
        

In [3]:
def QR_GS_gen(A): #This uses Gram-Schmitz, but can accept non-square matrix inputs.
    n = np.shape(A)
    Q = np.zeros((n[0],n[1]))
    R = np.zeros((n[1],n[1]))
    for j in range(0,n[1]):
        S = A[:,j]
        for i in range(0,j):
            R[i,j] = np.dot(np.matrix.getH(Q[:,i]),A[:,j])
            S = S - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(S)
        Q[:,j] = S/R[j,j]
    return Q, R

In [4]:
def QREig(A, maxiter = 2000, tol = 1e-7, printiter = False):
    n = np.shape(A)[0]
    eig = np.empty(n, dtype = "cfloat")
    ev = np.eye(n)
    if n == 1:
        return A[0,0]
    if n == 2:
        alpha = np.matrix.trace(A[0:2,0:2])
        beta = np.linalg.det(A[0:2,0:2])
        eig[0] = 0.5*(alpha+np.sqrt(alpha**2 - 4*beta + 0j))
        eig[1] = 0.5*(alpha-np.sqrt(alpha**2 - 4*beta + 0j))
        v2_1 = -(A[0,0] - eig1)/A[0,1]
        v2_2 = -(A[0,0] - eig2)/A[0,1]
        return eig, np.matrix([[1,1],[v2_1,v2_2]])
    if n == 3:
        for j in range(1,50):
            AO = A
            R,u,Q = QR_Householder(A) #QR algorithm goes here.
            ev = np.matmul(ev,Q)
            A = np.matmul(R,Q)
    for j in range(1,maxiter):
        AO = A
        R,u,Q = QR_Householder(A) #QR algorithm goes here.
        ev = np.matmul(ev,Q)
        A = np.matmul(R,Q)
        if np.linalg.norm(np.tril(A,-2)) < tol:
            i = 0
            while i < n-1:
                if abs(A[i+1,i]) < tol**0.5:
                    eig[i] = A[i,i]
                    i += 1
                else:
                    alpha = np.matrix.trace(A[i:(i+2),i:(i+2)])
                    beta = np.linalg.det(A[i:(i+2),i:(i+2)])
                    im = np.sqrt(alpha**2 - 4*beta + 0j)
                    eig[i] = 0.5*(alpha+im)
                    eig[i+1] = 0.5*(alpha-im)
                    i += 2
            if i >= n:
                if printiter == True:
                    print("Iterations used =",j)
                return eig, ev
            else:
                eig[n-1] = A[n-1,n-1]
                if printiter == True:
                    print("Iterations used =",j)
                return eig, ev

In [105]:
B = np.random.random((6,6))
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
u,s,vh = np.linalg.svd(C)
print(u*s@vh)
print(u)
print(np.diag(s))
print(vh)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [96]:
C = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.matrix.getH(C@np.matrix.getH(C))

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [119]:
Y = np.array([[1,2,1],[1,0,1],[2,3,1]])
np.linalg.pinv(Y)

array([[ 1.00000000e+00, -3.88578059e-16,  4.44089210e-16],
       [-2.22044605e-16,  1.00000000e+00,  2.22044605e-16],
       [-6.66133815e-16, -6.10622664e-16,  1.00000000e+00]])