In [1]:
import numpy as np
import math
import scipy as sc
import time
from scipy.integrate import quad
from scipy import linalg as la
from scipy import sparse
from math import pi
from math import factorial
from matplotlib import pyplot as plt

In [2]:
def pwrmtd (A,v0,tol=1e-8,maxiter=100,small=False):
    if small == True:
        A = np.linalg.inv(A)
    print("iter"," v_{k+1} - v_k")
    for k in range(0,maxiter):
        matm = A@v0
        matn = np.linalg.norm(matm,ord=np.inf)
        v1 = matm/matn
        change = np.linalg.norm((v1 - v0),ord=np.inf)
        print('{:>3d}  {:> 10.20f}'.format(k+1, change))
        if (change < tol):
            return v1, np.dot(v1,A@v1)/np.dot(v1,v1)
        v0 = v1

In [3]:
def pwrmtd_fixosc (A,v0,tol=1e-8,maxiter=100,small=False):
    if small == True:
        A = np.linalg.inv(A)
    print("iter"," v_{k+1} - v_k")
    matm = A@v0
    matn = np.linalg.norm(matm,ord=np.inf)
    v1 = matm/matn
    change = np.linalg.norm((v1 - v0),ord=np.inf)
    print('{:>3d}  {:> 10.20f}'.format(1, change))
    if (change < tol):
        return v1, np.dot(v1,A@v1)/np.dot(v1,v1)
    for k in range(1,maxiter):
        matm = A@v1
        matn = np.linalg.norm(matm,ord=np.inf)
        v2 = matm/matn
        change = np.linalg.norm((v2 - v0),ord=np.inf)
        print('{:>3d}  {:> 10.20f}'.format(k+1, change))
        if (change < tol):
            return v2, np.dot(v2,A@v2)/np.dot(v2,v2)
        v0 = v1
        v1 = v2

In [4]:
def pwrmtd_v2 (A,v0,tol=1e-8,maxiter=100,small=False): #Use lambda*I - A method instead to find the smallest eigenvalue.
    print("iter"," v_{k+1} - v_k")
    for k in range(0,maxiter):
        matm = A@v0
        matn = np.linalg.norm(matm,ord=np.inf)
        v1 = matm/matn
        change = np.linalg.norm((v1 - v0),ord=np.inf)
        print('{:>3d}  {:> 10.20f}'.format(k+1, change))
        if (change < tol):
            return v1, np.dot(v1,A@v1)/np.dot(v1,v1)
        v0 = v1

In [12]:
A = np.diag([4,3,2])
q = 4
C = np.diag([q,q,q])
#A[0,1], A[0,2], A[1,2] = 3,2,1
v1 = np.random.random(3)

e1,lamb = pwrmtd_fixosc(C-A,v1)

print(lamb)
print("q = ",q) #Need to remove the first basis vector; try projection?

iter  v_{k+1} - v_k
  1   0.74861015293093990941
  2   0.74861015293093990941
  3   0.16691677054997808294
  4   0.08345838527498904147
  5   0.04172919263749452073
  6   0.02086459631874726037
  7   0.01043229815937363018
  8   0.00521614907968681509
  9   0.00260807453984340755
 10   0.00130403726992170377
 11   0.00065201863496085189
 12   0.00032600931748042594
 13   0.00016300465874021297
 14   0.00008150232937010649
 15   0.00004075116468505324
 16   0.00002037558234252662
 17   0.00001018779117126331
 18   0.00000509389558563166
 19   0.00000254694779281583
 20   0.00000127347389640791
 21   0.00000063673694820396
 22   0.00000031836847410198
 23   0.00000015918423705099
 24   0.00000007959211852549
 25   0.00000003979605926275
 26   0.00000001989802963137
 27   0.00000000994901481569
2.0
q =  4


In [ ]:

Iu1 = np.diag([u1,u1,u1])
e2,u2 = pwrmtd_fixosc(Iu1-A,v1)

In [6]:
A = np.diag([0,-1,-2])
pwrmtd_fixosc(A,np.ones(3))

iter  v_{k+1} - v_k
  1   2.00000000000000000000
  2   1.00000000000000000000
  3   0.37500000000000000000
  4   0.18750000000000000000
  5   0.09375000000000000000
  6   0.04687500000000000000
  7   0.02343750000000000000
  8   0.01171875000000000000
  9   0.00585937500000000000
 10   0.00292968750000000000
 11   0.00146484375000000000
 12   0.00073242187500000000
 13   0.00036621093750000000
 14   0.00018310546875000000
 15   0.00009155273437500000
 16   0.00004577636718750000
 17   0.00002288818359375000
 18   0.00001144409179687500
 19   0.00000572204589843750
 20   0.00000286102294921875
 21   0.00000143051147460938
 22   0.00000071525573730469
 23   0.00000035762786865234
 24   0.00000017881393432617
 25   0.00000008940696716309
 26   0.00000004470348358154
 27   0.00000002235174179077
 28   0.00000001117587089539
 29   0.00000000558793544769


(array([ 0.00000000e+00, -1.86264515e-09, -1.00000000e+00]), -2.0)

In [7]:
A = np.diag([0,-1,-2])
A

array([[ 0,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -2]])

In [8]:
np.linalg.eig(A)

(array([ 0., -1., -2.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))