In [1]:
import numpy as np
import math
import scipy as sc
import time
from scipy.integrate import quad
from scipy import linalg as la
from scipy import sparse
from math import pi
from math import factorial
from matplotlib import pyplot as plt

In [61]:
def pwrmtd (A,v0,tol=1e-8,maxiter=100,small=False):
    if small == True:
        A = np.linalg.inv(A)
    print("iter"," v_{k+1} - v_k")
    for k in range(0,maxiter):
        matm = A@v0
        matn = np.linalg.norm(matm,ord=np.inf)
        v1 = matm/matn
        change = np.linalg.norm((v1 - v0),ord=np.inf)
        print('{:>3d}  {:> 10.20f}'.format(k+1, change))
        if (change < tol):
            return v1, np.dot(v1,A@v1)/np.dot(v1,v1)
        v0 = v1

In [141]:
def pwrmtd_fixosc (A,v0,tol=1e-8,maxiter=100,small=False):
    if small == True:
        A = np.linalg.inv(A)
    print("iter"," v_{k+1} - v_k")
    matm = A@v0
    matn = np.linalg.norm(matm,ord=np.inf)
    v1 = matm/matn
    change = np.linalg.norm((v1 - v0),ord=np.inf)
    print('{:>3d}  {:> 10.20f}'.format(1, change))
    if (change < tol):
        return v1, np.dot(v1,A@v1)/np.dot(v1,v1)
    for k in range(1,maxiter):
        matm = A@v1
        matn = np.linalg.norm(matm,ord=np.inf)
        v2 = matm/matn
        change = np.linalg.norm((v2 - v0),ord=np.inf)
        print('{:>3d}  {:> 10.20f}'.format(k+1, change))
        if (change < tol):
            return v2, np.dot(v2,A@v2)/np.dot(v2,v2)
        v0 = v1
        v1 = v2

In [ ]:
def pwrmtd_v2 (A,v0,tol=1e-8,maxiter=100,small=False): #Use lambda*I - A method instead to find the smallest eigenvalue.
    print("iter"," v_{k+1} - v_k")
    for k in range(0,maxiter):
        matm = A@v0
        matn = np.linalg.norm(matm,ord=np.inf)
        v1 = matm/matn
        change = np.linalg.norm((v1 - v0),ord=np.inf)
        print('{:>3d}  {:> 10.20f}'.format(k+1, change))
        if (change < tol):
            return v1, np.dot(v1,A@v1)/np.dot(v1,v1)
        v0 = v1

In [155]:
A = np.diag([4,3,2])
q = 4*np.random.random(1)[0]
C = np.diag([q,q,q])
#A[0,1], A[0,2], A[1,2] = 3,2,1
v1 = np.random.random(3)

e1,u1 = pwrmtd_fixosc(C-A,v1)
u1 = np.abs(u1)
Iu1 = np.diag([u1,u1,u1])
e2,u2 = pwrmtd_fixosc(Iu1-A,v1)

print(-(u2-u1))
print("q = ",q) #Need to remove the first basis vector; try projection?

iter  v_{k+1} - v_k
  1   1.88938927420857583073
  2   0.64418409524892339402
  3   0.36276865926116230732
  4   0.23163225171858792262
  5   0.14790004226246394881
  6   0.09443599645102118689
  7   0.06029854548568073375
  8   0.03850136308536183938
  9   0.02458359397380294534
 10   0.01569692717966586840
 11   0.01002268110782734804
 12   0.00639960518637875016
 13   0.00408622663945094368
 14   0.00260910597805280716
 15   0.00166594626421054186
 16   0.00106372718417070298
 17   0.00067920289306566261
 18   0.00043367940277695813
 19   0.00027690963379744686
 20   0.00017681020772220582
 21   0.00011289549274994496
 22   0.00007208516096128176
 23   0.00004602726206548607
 24   0.00002938897305622753
 25   0.00001876522083957127
 26   0.00001198182435582800
 27   0.00000765054225160897
 28   0.00000488496534462921
 29   0.00000311911046739332
 30   0.00000199159040473010
 31   0.00000127165497396691
 32   0.00000081196734477838
 33   0.00000051845113846392
 34   0.000000331037429

In [153]:
A = np.diag([0,-1,-2])
pwrmtd_fixosc(A,np.ones(3))

iter  v_{k+1} - v_k
  1   2.00000000000000000000
  2   1.00000000000000000000
  3   0.37500000000000000000
  4   0.18750000000000000000
  5   0.09375000000000000000
  6   0.04687500000000000000
  7   0.02343750000000000000
  8   0.01171875000000000000
  9   0.00585937500000000000
 10   0.00292968750000000000
 11   0.00146484375000000000
 12   0.00073242187500000000
 13   0.00036621093750000000
 14   0.00018310546875000000
 15   0.00009155273437500000
 16   0.00004577636718750000
 17   0.00002288818359375000
 18   0.00001144409179687500
 19   0.00000572204589843750
 20   0.00000286102294921875
 21   0.00000143051147460938
 22   0.00000071525573730469
 23   0.00000035762786865234
 24   0.00000017881393432617
 25   0.00000008940696716309
 26   0.00000004470348358154
 27   0.00000002235174179077
 28   0.00000001117587089539
 29   0.00000000558793544769


(array([ 0.00000000e+00, -1.86264515e-09, -1.00000000e+00]), -2.0)

In [86]:
A = np.diag([0,-1,-2])
A

array([[ 0,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -2]])

In [87]:
np.linalg.eig(A)

(array([ 0., -1., -2.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))