In [1]:
import numpy as np
import math
import time
import scipy
from math import pi, exp, factorial, sin, cos
from matplotlib import pyplot as plt

In [2]:
def QR_GS(A): #This uses Gram-Schmitz.
    n = np.shape(A)[0]
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
    for j in range(0,n):
        S = A[:,j]
        for i in range(0,j):
            R[i,j] = np.dot(np.matrix.getH(Q[:,i]),A[:,j])
            S = S - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(S)
        Q[:,j] = S/np.linalg.norm(S)
    return Q, R

In [3]:
def QR_GS_gen(A): #This uses Gram-Schmitz, but can accept non-square matrix inputs.
    n = np.shape(A)
    Q = np.zeros((n[0],n[1]))
    R = np.zeros((n[1],n[1]))
    for j in range(0,n[1]):
        S = A[:,j]
        for i in range(0,j):
            R[i,j] = np.matmul(np.matrix.getH(Q[:,i]),A[:,j])
            S = S - R[i,j]*Q[:,i]
        R[j,j] = np.linalg.norm(S)
        Q[:,j] = S/R[j,j]
    return Q, R

In [4]:
def QR_GS_modified(A): #This uses a modified version of Gram-Schmitz which avoids possible numerical instability.
    n = np.shape(A)
    Q = np.zeros((n[0],n[1]))
    R = np.zeros((n[1],n[1]))
    S = np.copy(A)*1.0
    for j in range(0,n[1]):
        R[j,j] = np.linalg.norm(S[:,j])
        Q[:,j] = S[:,j]/R[j,j]
        for i in range(j+1,n[1]):
            R[j,i] = np.matmul(np.matrix.getH(Q[:,j]),A[:,i])
            S[:,i] -= R[j,i]*Q[:,j]
    return Q, R

In [5]:
def QR_Householder(A):
    n = np.shape(A)[0]
    R = np.copy(A)*1.0
    Q = np.eye(n)*1.0
    V = np.zeros((n,n))
    for k in range(0,n):
        x = R[k:,k]
        e1 = np.zeros(np.size(x))
        e1[0] = 1
        v = np.sign(x[0])*np.linalg.norm(x,2)*e1 + x
        v = v/np.linalg.norm(v,2)
        V[0:(n-k),k] = v
        F = np.eye(n-k,n-k) - 2*np.outer(v,v)
        R[k:,k:] =  F@R[k:,k:]
        Q[k:,:] = F@np.copy(Q[k:,:]) #Modification to get Q.
    return R, V, np.matrix.getH(Q)
        

In [6]:
B = np.array([[1,2,3],[4,5,6],[7,8,20],[1,2,3]])
#print(B, "Input Array")
A = np.random.random((10,10))
Q,R = QR_GS_modified(B)
print(Q, "Modified Gram-Schmitz")
#print(R)
#print(Q@R)
print(np.allclose(Q@R,B))
print(np.dot(Q[2],Q[1]))

[[ 0.12216944  0.66303852  0.21320072]
 [ 0.48867778  0.18417737 -0.85280287]
 [ 0.85518611 -0.29468379  0.42640143]
 [ 0.12216944  0.66303852  0.21320072]] Modified Gram-Schmitz
True
-1.609823385706477e-15


In [7]:
B = np.array([[1,2,3],[4,5,6],[7,8,20],[1,2,3]])
A = np.random.random((10,10))
Q,R = QR_GS_gen(B)
#print(Q, "Gram-Schmitz")
#print(R)
print(np.allclose(B,Q@R))
print(np.dot(Q[2],Q[1]))

True
-1.609823385706477e-15


In [8]:
B = np.array([[1,2,3],[4,5,6],[7,8,20]])
R,V,Q = QR_Householder(B)

print(Q)
print(R)
print(Q@R)

[[-0.12309149  0.90453403 -0.40824829]
 [-0.49236596  0.30151134  0.81649658]
 [-0.86164044 -0.30151134 -0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -2.05562790e+01]
 [ 7.21644966e-16  9.04534034e-01 -1.50755672e+00]
 [ 7.77156117e-16 -6.17221305e-17 -4.49073120e+00]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 20.]]
